### PR TITLE
Pr2 - for adding Contributing.md

### PR DESCRIPTION
**Pull request by Shash-cre-dev**
Contributing.md contains all the guidelines in order for a contributor to contribute to the Project.

I have written the basic guidelines for now, it's still not completely finished. Do let me know  @rohitranjan-2702  that my way of writing is acceptable or I have to make any changes. Thank You

### CODE REVIEW

**Comment by rohitranjan-2702** [comment]
Well done @Shash-cre-dev , one thing, I think you should simplify the cloning steps, just fork the repo > clone > npm i > change the code

Don't make it too complex. Else everything is perfect.

**Comment by Shash-cre-dev** [comment]
Roger that, on it

**Comment by Shash-cre-dev** [comment]
@rohitranjan-2702 I have modified the ReadME.md with a better outlook on the Project. Do give it a check and let me know. 

Now I will start working on CONTRIBUTING.md, will keep it short and simple. 

Should I also add a CODE_OF_CONDUCT.md to specify the appropriate guidelines that need to be followed? It will follow the standard guidelines laid down by GitHub.

**Comment by Shash-cre-dev** [comment]
Final drafts of ReadME.md, CONTRIBUTION.md and CODE_OF_CONDUCT.md have been updated. @rohitranjan-2702, @mohammadshaad give it a read and let me know if any changes are required.

**Comment by rohitranjan-2702** [comment]
@Shash-cre-dev Good work man !!! Keep it up.

**Pull request merged**
